### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported.

### ISSUE THREAD

**Issue by bchabrier** [RogerHardiman/onvif-audit#5]
When installing the package, I get the following error:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/agsh/onvif.git
npm ERR!
npm ERR! fatal: remote error:
npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by gxj1134506645** [comment]
Have you solved this problem of github？Now I also have this problem. If you have solved this successfully, please help me,thank you!
![image](https://user-images.githubusercontent.com/49182687/165669404-05631572-1b35-4a75-a5b9-784f96b35c6f.png)

**Comment by bchabrier** [comment]
Just apply manually the change of #6  :
in package.json, replace  `"onvif": "git://github.com/agsh/onvif.git#cc4e57f"` by:
 ` "onvif": "https://github.com/agsh/onvif.git#cc4e57f"`

**Comment by RogerHardiman** [comment]
The fix is already in the master branch.
@gxj1134506645  - were you using old source code when reporting the issue? Just checking where you got the source from in case I need to update something

Thanks

**Comment by gxj1134506645** [comment]
thank you , I have solved this problem,thanks!
